LIBNAME = libdraw.a
SRCS = alloc.c allocimagemix.c arith.c bezier.c border.c buildfont.c \
	bytesperline.c chan.c cloadimage.c computil.c creadimage.c cursor.c \
	debug.c draw.c drawclient.c drawfcall.c drawrepl.c egetrect.c \
	ellipse.c emenuhit.c event.c font.c freesubfont.c getrect.c \
	getsubfont.c icossin.c icossin2.c init.c iprint.c keyboard.c \
	line.c loadimage.c menuhit.c mkfont.c mouse.c openfont.c poly.c \
	readimage.c readsubfont.c rectclip.c replclipr.c rgb.c scroll.c \
	snarf.c string.c stringbg.c stringsubfont.c stringwidth.c subfont.c \
	subfontcache.c subfontname.c unloadimage.c window.c writeimage.c \
	writesubfont.c wsys.c unix.c
include ../mklib.mk
