LIBNAME = libbio.a
SRCS = bbuffered.c bfildes.c bflush.c bgetc.c bgetrune.c bgetd.c binit.c \
	boffset.c bprint.c bputc.c bputrune.c brdline.c brdstr.c bread.c \
	bseek.c bvprint.c bwrite.c
include ../mklib.mk
