LIBNAME = libmemdraw.a
SRCS = alloc.c alloc-stub.c arc.c cload.c cload-stub.c cmap.c cread.c \
	draw.c draw-stub.c ellipse.c fillpoly.c hwdraw.c iprint.c line.c \
	load.c load-stub.c openmemsubfont.c poly.c read.c string.c subfont.c \
	unload.c unload-stub.c write.c
include ../mklib.mk
