LIBNAME = libndb.a
SRCS = ipattr.c ndbaux.c ndbcache.c ndbcat.c ndbconcatenate.c ndbdiscard.c \
	ndbfree.c ndbgetipaddr.c ndbgetval.c ndbhash.c ndbipinfo.c \
	ndblookval.c ndbopen.c ndbparse.c ndbreorder.c ndbsubstitute.c \
	sysdnsquery.c
include ../mklib.mk
