LIBNAME = libauth.a
SRCS = amount_getkey.c attr.c auth_attr.c auth_challenge.c auth_getkey.c \
	auth_getuserpasswd.c auth_proxy.c auth_respond.c auth_rpc.c \
	auth_userpasswd.c fsamount.c nsamount.c
include ../mklib.mk
